### ISSUE TITLE
Support for specifying the output file name

### ISSUE THREAD

**Issue by AnuradhaKaruppiah** [rapidsai/dependency-file-generator#117]
We have a need to provide requirements files as a part of the python package. We would like to generate it from a parent dependencies files that has multiple file keys. All of this is easily possible with this tool, only the name of the file is auto generated.

For example this snippet -
```
  # morpheus-llm pip dependencies are published as a morpheus_llm package data file
  morpheus_llm:
    output: requirements
    requirements_dir: python/morpheus_llm/morpheus_llm
    includes:
      - morpheus_core_pip
      - morpheus_llm_pip
```

Generates `python/morpheus_llm/morpheus_llm/requirements_morpheus_llm.txt`. I would like to instead get `python/morpheus_llm/morpheus_llm/requirements.txt`. Can you please provide an option for `output_file_name`? And maybe add a sanity checker for dup file names?
