### ISSUE TITLE
Support generating "project" dependency in pyproject.yaml with an extra

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/dependency-file-generator#147]
Trying to support this use case in https://github.com/rapidsai/cudf/pull/19223

For a yaml like

```yaml
files:
  py_run_cudf:
    output: pyproject
    pyproject_dir: python/cudf
    extras:
      table: project
    includes:
      - depends_on_pylibcudf_pyarrow
dependencies:
  depends_on_pylibcudf_pyarrow:
      specific:
        - output_types: [requirements, pyproject]
          matrices:
            - matrix:
                cuda: "12.*"
                cuda_suffixed: "true"
              packages:
                - pylibcudf-cu12[pyarrow]==25.8.*,>=0.0.0a0
```

I would expect the resulting `python/cudf/pyproject.toml` to have a `dependencies` section like

```yaml
dependencies = [
     "pylibcudf-cu12[pyarrow]==25.8.*,>=0.0.0a0",
]
```

Instead I see

```yaml
dependencies = [
     "pylibcudf==25.8.*,>=0.0.0a0",
]
```

I'm not sure this is a user error or not a supported functionality.

**Comment by jameslamb** [comment]
By convention in RAPIDS, we don't pass through any selectors (like `cuda=12.x`) to `rapids-dependency-file-generator` when running the `pre-commit hook` that populates files like `pyproject.toml` in source control.

When there aren't any selectors, the only matrix that matches is one that has 0 selectors... we often call this the "fallback matrix".

There's on in exactly the part of `cudf`'s `dependencies.yaml`, but you've omitted it here.

```yaml
  depends_on_pylibcudf:
    common:
      - output_types: conda
        packages:
          - &pylibcudf_unsuffixed pylibcudf==25.8.*,>=0.0.0a0
      - output_types: requirements
        packages:
          # pip recognizes the index as a global option for the requirements.txt file
          - --extra-index-url=https://pypi.nvidia.com
          - --extra-index-url=https://pypi.anaconda.org/rapidsai-wheels-nightly/simple
    specific:
      - output_types: [requirements, pyproject]
        matrices:
          - matrix:
              cuda: "12.*"
              cuda_suffixed: "true"
            packages:
              - pylibcudf-cu12==25.8.*,>=0.0.0a0
          - {matrix: null, packages: [*pylibcudf_unsuffixed]}
```

([cudf/dependencies.yaml](https://github.com/rapidsai/cudf/blob/e993f37c506e1c7a956bde75a8b5ffb737065470/dependencies.yaml#L937))

Specifically, in case it's hard to see there, I'm referring to this:

```yaml
              - pylibcudf-cu12==25.8.*,>=0.0.0a0
          - {matrix: null, packages: [*pylibcudf_unsuffixed]}
```

It's intentional that `pyproject.toml` in source control contain the unsuffixed dependencies instead of those referring to a specific CUDA version.

But that's only for the one in source control... at build time, the correct CUDA-version-specific dependency metadata is written into the produced wheels by `rapids-build-backend`.

So e.g. `cudf-cu12` wheels will have the correct dependency on `pylibcudf-cu12==25.8.*,>=0.0.0a0`.

So this is working as intended. For more details on how `rapids-dependency-file-generator` chooses which matrices to use, please see https://github.com/rapidsai/dependency-file-generator?tab=readme-ov-file#how-dependency-lists-are-merged
