### ISSUE TITLE
Support matrix globs

### ISSUE THREAD

**Issue by bdice** [rapidsai/dependency-file-generator#41]
Feature proposal: `matrix:` entries should be interpreted as globs, so that `matrix: cuda: "11.*"` can match any of `11.2, 11.4, 11.5, 11.8`. This will be really helpful when delineating CUDA 11 from CUDA 12, so that we don't have to specify every version individually if the match is major-version-only and not specific to minor versions.

We would keep the current behavior of taking the first match. If a specific match is to take precedence, it should be listed before the glob match. e.g. `11.8` before `11.*`.

Example:
```yaml
  cuda-python:
    specific:
      - output_types: conda
        matrices:
          - matrix:
              cuda: "11.*"
            packages:
              - cuda-python>=11.7.0
          - matrix:
              cuda: "12.*"
            packages:
              - cuda-python>=12.1.0
```
